import { TreeSettings, TreeDataType, TreeDataFormat } from '../types';

export const defaultSettings: TreeSettings = {
  containerid: null,
  url: null,
  async: false,
  dataset: null,
  datatype: TreeDataType.Json,
  dataformat: TreeDataFormat.Hierarchy,
  class_node_collapse: 'ui-icon-folder-collapsed',
  class_node_expand: 'ui-icon-folder-open',
  class_node_item: 'ui-icon-document',
  collapse_tree: false,
  class_node_highlight: 'ui-state-highlight',
  class_node_add: 'ui-icon-plusthick',
  class_node_remove: 'ui-icon-minusthick',
  show_button_check: false,
  show_button_add: false,
  show_button_remove: false,
  node_remove_message: 'Are you sure you want to remove this node?',
  onstart: () => {},
  onend: () => {},
  onprocessingstart: () => {},
  onprocessingcomplete: () => {},
  onprocessingerror: () => {},
  onbeforedataconversion: () => {},
  onafterdataconversion: () => {},
  onrenderstart: () => {},
  onrendercomplete: () => {},
  onbeforenodeinsert: () => {},
  onafternodeinsert: () => {},
  onselectednode: () => {},
  onbeforeaddnode: () => {},
  onafteraddnode: () => {},
  onbeforeremovenode: () => {},
  onafterremovenode: () => {},
  onaddnode: () => {},
  onremovenode: () => {},
  onnodecheckselected: () => {},
};
