name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install --prefix src
      - name: Lint
        run: npm run lint --prefix src
      - name: Test
        run: npm test --prefix src
      - name: Build
        run: npm run build --prefix src
